language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

matrix:
  include:
    - env: JDK='Oracle JDK 8'
      jdk: oraclejdk8
    - env: JDK='OpenJDK 8'
      jdk: openjdk8
    - env: JDK='Oracle JDK 9'
      jdk: oraclejdk9
#    - env: JDK='Oracle JDK 10'
#      jdk: oraclejdk10

#addons:
#  apt:
#    packages:
#      - oracle-java8-installer

sudo: required

services:
  - docker

before_install:
 - cp gradle.properties.ci gradle.properties

before_script:
  - chmod +x gradlew
  
script:
  - java -version
  - ./gradlew check --parallel
  - ./gradlew codeCoverageReport

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
 - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
