version: "3"
services:

  redis:
#      image: redis:4.0-alpine
      image: grokzen/redis-cluster
      ports:
      - '7000-7007:7000-7007'
      environment:
        - IP=0.0.0.0
        - STANDALONE=true
